# Generated by Django 6.0.1 on 2026-07-01 11:07

import django.db.models.deletion
import textbook.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0031_quiz_is_self_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('material', 'Учебный материал'), ('ege', 'Теория ЕГЭ')], default='material', max_length=10, verbose_name='Вкладка')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL-идентификатор')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок статьи')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='textbook/articles/', verbose_name='Превью изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EgeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер задания ЕГЭ')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Задание ЕГЭ',
                'verbose_name_plural': 'Задания ЕГЭ',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название блока')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='textbook/sections/', verbose_name='Превью изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Блок учебника',
                'verbose_name_plural': 'Блоки учебника',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текст (Markdown)'), ('code', 'Код (только чтение)'), ('image', 'Изображение'), ('video', 'Видео'), ('formula', 'Формула (LaTeX)'), ('widget', 'Интерактивный виджет')], default='text', max_length=20, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (необязательно)')),
                ('content', models.TextField(blank=True, help_text='text — Markdown; code — исходный код; formula — LaTeX; image/video — подпись/описание', verbose_name='Содержимое')),
                ('code_language', models.CharField(blank=True, choices=[('python', 'Python'), ('cpp', 'C++'), ('c', 'C'), ('bash', 'Bash'), ('sql', 'SQL')], default='python', max_length=20, verbose_name='Язык кода')),
                ('image', models.ImageField(blank=True, null=True, upload_to=textbook.models.article_image_upload, verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo или прямая ссылка', verbose_name='URL видео')),
                ('widget_key', models.CharField(blank=True, help_text='Идентификатор компонента в реестре (напр. bits-viewer, embed)', max_length=50, verbose_name='Ключ виджета')),
                ('widget_config', models.JSONField(blank=True, help_text='Параметры в формате JSON, напр. {"value": 42, "bits": 8}', null=True, verbose_name='Конфигурация виджета')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='textbook.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Блок статьи',
                'verbose_name_plural': 'Блоки статьи',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='ege_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='textbook.egetask', verbose_name='Задание ЕГЭ (для вкладки ЕГЭ)'),
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='textbook.section', verbose_name='Блок (для учебного материала)'),
        ),
        migrations.CreateModel(
            name='ArticleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('reading', 'Читается'), ('read', 'Прочитано'), ('mastered', 'Освоено')], default='reading', max_length=20, verbose_name='Статус')),
                ('first_opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Впервые открыто')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано (долистано)')),
                ('mastered_at', models.DateTimeField(blank=True, null=True, verbose_name='Освоено (самопроверка)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='textbook.article', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_progress', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Прогресс по статье',
                'verbose_name_plural': 'Прогресс по статьям',
                'indexes': [models.Index(fields=['user', 'article'], name='textbook_ar_user_id_895747_idx'), models.Index(fields=['article', 'status'], name='textbook_ar_article_a5ac5f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'article'), name='unique_user_article_progress')],
            },
        ),
        migrations.CreateModel(
            name='ArticleQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Подпись (напр. «Разминка»)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_check_quizzes', to='textbook.article', verbose_name='Статья')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quizzes.quiz', verbose_name='Тест самопроверки')),
            ],
            options={
                'verbose_name': 'Самопроверка статьи',
                'verbose_name_plural': 'Самопроверки статьи',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('article', 'quiz'), name='unique_article_quiz')],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['track', 'is_published'], name='textbook_ar_track_8ccb1c_idx'),
        ),
    ]
