# Generated by Django 6.0.1 on 2026-08-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlequiz',
            name='is_practicum',
            field=models.BooleanField(default=False, help_text='Обязательные задачи блока: считаются отдельно от микротестов после статей и определяют, пройден ли блок', verbose_name='Практикум блока'),
        ),
    ]
