# Generated by Django 6.0.1 on 2026-08-13 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0031_quiz_is_self_check'),
        ('textbook', '0002_articlequiz_is_practicum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlequiz',
            name='is_practicum',
        ),
        migrations.AddField(
            model_name='section',
            name='practicum_quiz',
            field=models.ForeignKey(blank=True, help_text='Обязательные задачи блока: отдельная страница задач, не статья. Определяет, пройден ли блок.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quizzes.quiz', verbose_name='Практикум блока'),
        ),
    ]
