# Generated by Django 6.0.1 on 2026-08-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0003_remove_articlequiz_is_practicum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleprogress',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Суммарное время с открытой и активной вкладкой статьи', verbose_name='Время чтения (секунды)'),
        ),
    ]
