# Generated by Django 6.0.1 on 2026-08-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0004_articleprogress_time_spent_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='После этого момента задачи блока и самопроверки уроков переходят в режим просмотра: решения больше не принимаются. Пусто — без ограничения по времени.', null=True, verbose_name='Дедлайн'),
        ),
        migrations.AddField(
            model_name='section',
            name='grade_3_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка 3 — от скольких задач'),
        ),
        migrations.AddField(
            model_name='section',
            name='grade_4_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка 4 — от скольких задач'),
        ),
        migrations.AddField(
            model_name='section',
            name='grade_5_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка 5 — от скольких задач'),
        ),
    ]
