# Generated by Django 6.0.1 on 2026-08-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0005_section_deadline_section_grade_3_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='hints_open',
            field=models.BooleanField(default=False, help_text='Аварийный рубильник: подсказки ко всем задачам блока предлагаются сразу, не дожидаясь трёх неудачных попыток и последних трёх дней до дедлайна.', verbose_name='Открыть подсказки блока'),
        ),
    ]
