# Generated by Django 6.0.1 on 2026-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0007_alter_articleblock_content_alter_section_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egetask',
            name='exam_unlock_threshold',
            field=models.PositiveSmallIntegerField(default=10, help_text='Сколько задач этого задания нужно решить верно в режиме «Учёба», чтобы открылся «Экзамен». 0 – экзамен доступен сразу.', verbose_name='Задач до открытия экзамена'),
        ),
    ]
