# Generated by Django 6.0.1 on 2026-08-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0008_egetask_exam_unlock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='egetask',
            name='classroom_enabled',
            field=models.BooleanField(default=False, help_text='Пока выключено, кнопка «Задачи для урока» ученикам не видна. Включайте перед занятием: набор задаёт учитель галочкой «Только для работы в классе» у нужных задач.', verbose_name='Показать задачи для урока'),
        ),
    ]
