# Generated by Django 6.0.1 on 2026-08-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0009_egetask_classroom_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='egetask',
            name='exam_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Сколько задач давать в режиме «Экзамен» по этому заданию. Пусто – по нормативу времени (сколько влезает в час, но не больше пяти). Ставьте меньше, если задачи номера тяжёлые.', null=True, verbose_name='Задач на экзамене'),
        ),
    ]
