# Generated by Django 6.0.1 on 2026-08-31 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0010_egetask_exam_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(help_text='До этого момента ученик сдаёт задачи блока и самопроверки, даже когда общий дедлайн уже прошёл.', verbose_name='Личный дедлайн')),
                ('reason', models.CharField(blank=True, help_text='Для себя: «болел, справка до 12.03». Ученику не показывается.', max_length=200, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='textbook.section', verbose_name='Блок учебника')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_extensions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Продление дедлайна',
                'verbose_name_plural': 'Продления дедлайнов',
                'ordering': ['-deadline'],
                'constraints': [models.UniqueConstraint(fields=('user', 'section'), name='unique_section_extension')],
            },
        ),
    ]
