# Generated by Django 6.0.1 on 2026-09-05 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spetskurs', '0003_coursetask'),
        ('textbook', '0011_sectionextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='course_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='spetskurs.coursetask', verbose_name='Задача спецкурса (для вкладки спецкурса)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='track',
            field=models.CharField(choices=[('material', 'Учебный материал'), ('ege', 'Теория ЕГЭ'), ('spetskurs', 'Спецкурс')], default='material', max_length=10, verbose_name='Вкладка'),
        ),
    ]
