# Generated by Django 6.0.1 on 2026-09-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0012_article_course_task_alter_article_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblock',
            name='visibility',
            field=models.CharField(choices=[('all', 'Всем'), ('teacher', 'Только учителю'), ('students', 'Открыт ученикам')], default='all', help_text='teacher – скрыт до разбора; students – учитель открыл его авторизованным. Гостю не виден ни в том, ни в другом случае', max_length=10, verbose_name='Кому виден'),
        ),
    ]
