# Generated by Django 6.0.1 on 2026-09-26 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0013_articleblock_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(verbose_name='Звёзды (1–5)')),
                ('comment', models.TextField(blank=True, max_length=2000, verbose_name='Что было непонятно')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='textbook.article', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка статьи',
                'verbose_name_plural': 'Оценки статей',
                'constraints': [models.UniqueConstraint(fields=('user', 'article'), name='unique_user_article_rating'), models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='article_rating_stars_1_5')],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField(blank=True, max_length=20000, verbose_name='Было')),
                ('proposed', models.TextField(max_length=20000, verbose_name='Стало / как лучше')),
                ('comment', models.TextField(blank=True, max_length=2000, verbose_name='Почему')),
                ('image', models.ImageField(blank=True, null=True, upload_to='textbook/suggestions/%Y/%m/', verbose_name='Картинка')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=10, verbose_name='Статус')),
                ('reply', models.TextField(blank=True, max_length=2000, verbose_name='Ответ учителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='textbook.article', verbose_name='Статья')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='textbook.articleblock', verbose_name='Блок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Предложение правки',
                'verbose_name_plural': 'Предложения правок',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='textbook_su_status_9d5ff0_idx')],
            },
        ),
    ]
