# Generated by Django 6.0.1 on 2026-10-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0014_article_rating_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='egetask',
            name='covered',
            field=models.BooleanField(default=False, help_text='Пометка учителя для себя: карточка на карте /ege/ закрашена. Ученики её не видят.', verbose_name='Разобрали на уроке'),
        ),
    ]
