# Generated by Django 6.0.1 on 2026-04-01 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('title', models.CharField(max_length=200, verbose_name='Название симуляции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='spetskurs/simulations/', verbose_name='Превью изображение')),
                ('wasm_path', models.CharField(blank=True, help_text='Относительный путь в static/, например: spetskurs/wasm/pendulum.wasm', max_length=300, verbose_name='Путь к .wasm файлу')),
                ('js_path', models.CharField(blank=True, help_text='Относительный путь в static/, например: spetskurs/wasm/pendulum.js', max_length=300, verbose_name='Путь к .js файлу (glue code)')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Семестр 1'), (2, 'Семестр 2')], default=1, verbose_name='Семестр')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Симуляция',
                'verbose_name_plural': 'Симуляции',
                'ordering': ['semester', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TheoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='spetskurs/theory/', verbose_name='Превью изображение')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Семестр 1'), (2, 'Семестр 2')], default=1, verbose_name='Семестр')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Страница теории',
                'verbose_name_plural': 'Страницы теории',
                'ordering': ['semester', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TheoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('formula', 'Формула (LaTeX)'), ('code', 'Код'), ('image', 'Изображение')], default='text', max_length=20, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (необязательно)')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('code_language', models.CharField(blank=True, choices=[('cpp', 'C++'), ('c', 'C'), ('python', 'Python'), ('bash', 'Bash')], default='cpp', max_length=20, verbose_name='Язык кода')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spetskurs/theory/images/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('theory_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='spetskurs.theorypage', verbose_name='Страница теории')),
            ],
            options={
                'verbose_name': 'Блок теории',
                'verbose_name_plural': 'Блоки теории',
                'ordering': ['order'],
            },
        ),
    ]
