# Generated by Django 6.0.1 on 2026-10-01 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spetskurs', '0003_coursetask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('group', models.CharField(choices=[('coulomb', 'Кулоновское взаимодействие'), ('stat', 'Статистические методы'), ('grid', 'Поля на сетке'), ('dynamics', 'Динамика и хаос')], max_length=20, verbose_name='Раздел')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(2, '★★'), (3, '★★★')], default=2, verbose_name='Сложность')),
                ('teaser', models.CharField(max_length=300, verbose_name='Зацепка для карточки')),
                ('phenomenon', models.TextField(verbose_name='Что за явление')),
                ('where', models.TextField(verbose_name='Где встречается')),
                ('research', models.TextField(verbose_name='Что вы исследуете')),
                ('result', models.TextField(verbose_name='Что получится в конце')),
                ('steps', models.TextField(verbose_name='Этапы работы (Markdown)')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='Заметки учителя (Markdown)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Тема проекта',
                'verbose_name_plural': 'Темы проектов',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spetskurs/projects/', verbose_name='Файл')),
                ('caption', models.CharField(max_length=300, verbose_name='Подпись')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('license', models.CharField(max_length=60, verbose_name='Лицензия')),
                ('source_url', models.URLField(verbose_name='Источник')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spetskurs.projecttopic')),
            ],
            options={
                'verbose_name': 'Иллюстрация',
                'verbose_name_plural': 'Иллюстрации',
                'ordering': ['order'],
            },
        ),
    ]
