# Generated by Django 6.0.1 on 2026-01-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageBlock',
        ),
    ]
