# Generated by Django 6.0.1 on 2026-01-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_delete_homepageblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Главная'), ('about', 'Обо мне')], max_length=20, verbose_name='Страница')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('text_image', 'Текст + Изображение')], default='text', max_length=20, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, help_text='Для главной страницы - заголовок карточки', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/', verbose_name='Изображение')),
                ('link_url', models.CharField(blank=True, help_text='Для главной страницы - ссылка на раздел', max_length=200, verbose_name='URL ссылки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
                'ordering': ['page', 'order'],
            },
        ),
    ]
