# Generated by Django 6.0.1 on 2026-01-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='image_width',
            field=models.PositiveIntegerField(default=50, help_text='Процент ширины для изображения (20-80)', verbose_name='Ширина изображения (%)'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='layout',
            field=models.CharField(choices=[('vertical', 'Вертикально'), ('horizontal', 'Горизонтально (текст слева)'), ('horizontal-reverse', 'Горизонтально (картинка слева)')], default='vertical', max_length=20, verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='text_align',
            field=models.CharField(choices=[('left', 'По левому краю'), ('center', 'По центру'), ('right', 'По правому краю')], default='left', max_length=10, verbose_name='Выравнивание текста'),
        ),
    ]
