# Generated by Django 6.0.1 on 2026-01-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contentblock_image_align_contentblock_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='image_crop_height',
            field=models.FloatField(default=0, verbose_name='Crop Height'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image_crop_width',
            field=models.FloatField(default=0, verbose_name='Crop Width'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image_crop_x',
            field=models.FloatField(default=0, verbose_name='Crop X'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image_crop_y',
            field=models.FloatField(default=0, verbose_name='Crop Y'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image_natural_height',
            field=models.PositiveIntegerField(default=0, verbose_name='Image Natural Height'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image_natural_width',
            field=models.PositiveIntegerField(default=0, verbose_name='Image Natural Width'),
        ),
    ]
