# Generated by Django 6.0.1 on 2026-01-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contentblock_image_crop_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='image_pos_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Image X'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image_pos_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='Image Y'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='text_pos_x',
            field=models.IntegerField(blank=True, null=True, verbose_name='Text X'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='text_pos_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='Text Y'),
        ),
    ]
