# Generated by Django 6.0.1 on 2026-01-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_contentblock_card_bg_contentblock_content_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='image_border_radius',
            field=models.CharField(default='0.5rem', max_length=20, verbose_name='Скругление углов изображения'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image_object_fit',
            field=models.CharField(choices=[('cover', 'Заполнить (cover)'), ('contain', 'Вместить (contain)'), ('fill', 'Растянуть (fill)'), ('none', 'Оригинал (none)')], default='cover', max_length=20, verbose_name='Заполнение изображения'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image_opacity',
            field=models.PositiveIntegerField(default=100, verbose_name='Прозрачность изображения (%)'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image_position_x',
            field=models.PositiveIntegerField(default=50, help_text='0 = левый край, 50 = центр, 100 = правый край', verbose_name='Позиция фокуса X (%)'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image_position_y',
            field=models.PositiveIntegerField(default=50, help_text='0 = верхний край, 50 = центр, 100 = нижний край', verbose_name='Позиция фокуса Y (%)'),
        ),
    ]
