# Generated by Django 6.0.1 on 2026-06-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_contentblock_image_border_radius_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('education', 'Образование'), ('publication', 'Публикация'), ('conference', 'Конференция'), ('award', 'Награда / грант')], max_length=20, verbose_name='Тип события')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Месяц (1–12)')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('doi_or_url', models.URLField(blank=True, verbose_name='DOI / ссылка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Событие / публикация',
                'verbose_name_plural': 'События / публикации',
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AuthorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/photos/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt-текст')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Фото автора',
                'verbose_name_plural': 'Фотографии автора',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('role', models.CharField(max_length=300, verbose_name='Должность / аффилиация')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('research_interests', models.TextField(blank=True, verbose_name='Научные интересы')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='about/portrait/', verbose_name='Портрет (hero)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Ссылка Telegram')),
                ('vk_url', models.URLField(blank=True, verbose_name='Ссылка ВКонтакте')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Профиль автора',
                'verbose_name_plural': 'Профиль автора',
            },
        ),
        migrations.CreateModel(
            name='AuthorVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video_file', models.FileField(upload_to='about/videos/', verbose_name='Видеофайл (MP4)')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='about/video_posters/', verbose_name='Постер (превью)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Видео автора',
                'verbose_name_plural': 'Видео автора',
                'ordering': ['order'],
            },
        ),
    ]
