# Generated by Django 6.0.1 on 2026-06-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_authorevent_authorphoto_authorprofile_authorvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorevent',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Показывать «настоящее время» вместо конечного года', verbose_name='Настоящее время'),
        ),
    ]
