# Generated by Django 6.0.1 on 2026-10-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_authorevent_is_current'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentBlock',
        ),
    ]
