# Generated by Django 6.0.1 on 2026-01-11 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': 'Учебный класс', 'verbose_name_plural': 'Учебные классы'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.studentgroup', verbose_name='Класс'),
        ),
    ]
