# Generated by Django 6.0.1 on 2026-02-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentgroup_options_alter_profile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_ege',
            field=models.BooleanField(default=False, verbose_name='Сдаёт ЕГЭ'),
        ),
    ]
