# Generated by Django 6.0.1 on 2026-08-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alumni_about',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='alumni_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Вуз / место работы'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='graduation_note',
            field=models.TextField(blank=True, verbose_name='Слово учителя о классе'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='graduation_photo',
            field=models.ImageField(blank=True, upload_to='alumni/', verbose_name='Общее фото класса'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Заполнено – класс уходит в архив выпускников и пропадает из активных списков', null=True, verbose_name='Год выпуска'),
        ),
    ]
