# Generated by Django 6.0.1 on 2026-08-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_alumni_about_profile_alumni_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alumni_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Вуз'),
        ),
    ]
