# Generated by Django 6.0.1 on 2026-09-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_alumni_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='no_textbook_deadlines',
            field=models.BooleanField(default=False, help_text='Блоки учебника у учеников этого класса не закрываются по сроку – например, у группы подготовки к ЕГЭ, где учебник – справочник.', verbose_name='Без дедлайнов учебника'),
        ),
    ]
