# Generated by Django 6.0.1 on 2026-09-28 16:41

from django.db import migrations, models


def hide_graduated(apps, schema_editor):
    # До галочки выпуск убирал класс из статистики – сохраняем это для уже выпущенных.
    apps.get_model('accounts', 'StudentGroup').objects.filter(
        graduation_year__isnull=False).update(in_stats=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentgroup_no_textbook_deadlines'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='in_stats',
            field=models.BooleanField(default=True, help_text='Снято – вкладки класса нет на страницах статистики учителя (учебник, ЕГЭ). Для классов, с которыми сейчас не работаете.', verbose_name='В статистике'),
        ),
        migrations.RunPython(hide_graduated, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentgroup',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Заполнено – класс появляется в архиве выпускников. Из статистики его убирает только галочка «В статистике»', null=True, verbose_name='Год выпуска'),
        ),
    ]
