# Generated by Django 6.0.1 on 2026-10-06 16:29

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_notification_status'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Заявка в класс',
                'verbose_name_plural': 'Заявки в классы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='join_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='accounts.studentgroup', verbose_name='Заявка в класс'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='is_ege_class',
            field=models.BooleanField(default=False, help_text='Принятые по коду ученики этого класса сразу получают «Сдаёт ЕГЭ». Читается только в момент принятия – уже принятых не трогает.', verbose_name='Класс подготовки к ЕГЭ'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='join_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=8, verbose_name='Код класса'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='join_code_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Код действует до'),
        ),
    ]
