# Generated by Django 6.0.1 on 2026-01-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_userresult_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_text_answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Правильный ответ (для свободного ввода)'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Выбор ответа'), ('text', 'Свободный ответ')], default='choice', max_length=10, verbose_name='Тип вопроса'),
        ),
    ]
