# Generated by Django 6.0.1 on 2026-01-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_code',
            field=models.TextField(blank=True, help_text='Код, который проверит решение ученика. Например: assert sum(2,2) == 4', null=True, verbose_name='Код проверки (Asserts)'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='code_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Код ученика'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_text_answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Правильный ответ (текст)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Выбор ответа'), ('text', 'Свободный ответ'), ('code', 'Написание кода (Python)')], default='choice', max_length=10, verbose_name='Тип вопроса'),
        ),
    ]
