# Generated by Django 6.0.1 on 2026-01-11 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_question_test_code_useranswer_code_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test_code',
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, help_text='То, что будет подано на вход программе', verbose_name='Входные данные (Stdin)')),
                ('output_data', models.TextField(help_text='То, что программа должна вывести', verbose_name='Ожидаемый вывод (Stdout)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='quizzes.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Тестовый пример',
                'verbose_name_plural': 'Тестовые примеры',
            },
        ),
    ]
