# Generated by Django 6.0.1 on 2026-01-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_remove_question_test_code_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='error_log',
            field=models.TextField(blank=True, null=True, verbose_name='Лог ошибки'),
        ),
    ]
