# Generated by Django 6.0.1 on 2026-01-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_useranswer_error_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Сколько раз ученик может пройти тест. 0 - безлимитно.', verbose_name='Максимум попыток'),
        ),
    ]
