# Generated by Django 6.0.1 on 2026-01-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_quiz_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Дата и время, после которого тест закрывается', null=True, verbose_name='Конец доступа'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Дата и время, с которого тест становится доступным', null=True, verbose_name='Начало доступа'),
        ),
    ]
