# Generated by Django 6.0.1 on 2026-01-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_quiz_end_date_quiz_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='question_files/', verbose_name='Файл с данными (для скачивания)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
    ]
