# Generated by Django 6.0.1 on 2026-01-17 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_question_data_file_alter_question_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userresult',
            index=models.Index(fields=['user', 'quiz'], name='quizzes_use_user_id_bfef70_idx'),
        ),
        migrations.AddIndex(
            model_name='userresult',
            index=models.Index(fields=['quiz', 'date_completed'], name='quizzes_use_quiz_id_c91f75_idx'),
        ),
    ]
