# Generated by Django 6.0.1 on 2026-01-18 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentgroup_options_alter_profile_group'),
        ('quizzes', '0011_userresult_quizzes_use_user_id_bfef70_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, help_text='Переопределяет глобальную дату начала', null=True, verbose_name='Начало доступа')),
                ('end_date', models.DateTimeField(blank=True, help_text='Переопределяет глобальную дату конца', null=True, verbose_name='Конец доступа')),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text='Переопределяет глобальное кол-во попыток', null=True, verbose_name='Максимум попыток')),
            ],
            options={
                'verbose_name': 'Назначение теста',
                'verbose_name_plural': 'Назначения тестов',
            },
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user_result', 'is_correct'], name='quizzes_use_user_re_5d2929_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question', 'is_correct'], name='quizzes_use_questio_43d4e6_idx'),
        ),
        migrations.AddField(
            model_name='quizassignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to='accounts.studentgroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='quizassignment',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quizzes.quiz', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='quizassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
    ]
