# Generated by Django 6.0.1 on 2026-02-04 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_quizassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('error', 'Системная ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('is_correct', models.BooleanField(null=True, verbose_name='Правильно?')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='Лог ошибки')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачи Celery')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quizzes.question', verbose_name='Вопрос')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quizzes.quiz', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отправка кода',
                'verbose_name_plural': 'Отправки кода',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='useranswer',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.codesubmission', verbose_name='Отправка кода'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['user', 'quiz', 'question'], name='quizzes_cod_user_id_433204_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['status'], name='quizzes_cod_status_e9dfd5_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['celery_task_id'], name='quizzes_cod_celery__332c61_idx'),
        ),
    ]
