# Generated by Django 6.0.1 on 2026-02-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_add_code_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, help_text='Используется для отображения и сортировки. Если пусто — берётся первая строка текста.', max_length=200, verbose_name='Заголовок вопроса'),
        ),
    ]
