# Generated by Django 6.0.1 on 2026-02-08 11:33

from django.db import migrations


def populate_titles(apps, schema_editor):
    Question = apps.get_model('quizzes', 'Question')
    for q in Question.objects.filter(title=''):
        first_line = q.text.strip().split('\n')[0][:200]
        q.title = first_line
        q.save(update_fields=['title'])


def reverse_titles(apps, schema_editor):
    Question = apps.get_model('quizzes', 'Question')
    Question.objects.all().update(title='')


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_add_title_to_question'),
    ]

    operations = [
        migrations.RunPython(populate_titles, reverse_titles),
    ]
