# Generated by Django 6.0.1 on 2026-02-08 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_populate_question_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('answered', 'Отвечен'), ('resolved', 'Решён')], default='open', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('has_unread_for_teacher', models.BooleanField(default=True, verbose_name='Непрочитано учителем')),
                ('has_unread_for_student', models.BooleanField(default=False, verbose_name='Непрочитано учеником')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='quizzes.question', verbose_name='Вопрос')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='quizzes.quiz', verbose_name='Тест')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Запрос помощи',
                'verbose_name_plural': 'Запросы помощи',
            },
        ),
        migrations.CreateModel(
            name='HelpComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('line_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер строки')),
                ('code_snapshot', models.TextField(blank=True, null=True, verbose_name='Снапшот кода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quizzes.helprequest', verbose_name='Запрос помощи')),
            ],
            options={
                'verbose_name': 'Комментарий помощи',
                'verbose_name_plural': 'Комментарии помощи',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['status', 'has_unread_for_teacher'], name='quizzes_hel_status_3d17f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helprequest',
            unique_together={('student', 'question')},
        ),
    ]
