# Generated by Django 6.0.1 on 2026-02-10 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_helprequest_helpcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcomment',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000, message='Комментарий не может превышать 10000 символов')], verbose_name='Текст комментария'),
        ),
    ]
