# Generated by Django 6.0.1 on 2026-02-14 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_alter_helpcomment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='question_files/', verbose_name='Файл')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание файла')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='quizzes.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Файл вопроса',
                'verbose_name_plural': 'Файлы вопросов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='question_images/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Альтернативный текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quizzes.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Изображение вопроса',
                'verbose_name_plural': 'Изображения вопросов',
                'ordering': ['order', 'id'],
            },
        ),
    ]
