# Generated by Django 6.0.1 on 2026-02-14 12:29

from django.db import migrations


def migrate_data_files(apps, schema_editor):
    """Переносим существующие data_file в QuestionFile."""
    Question = apps.get_model('quizzes', 'Question')
    QuestionFile = apps.get_model('quizzes', 'QuestionFile')

    for question in Question.objects.exclude(data_file='').exclude(data_file__isnull=True):
        QuestionFile.objects.create(
            question=question,
            file=question.data_file,
            description='',
            order=0,
        )


def reverse_migrate(apps, schema_editor):
    """Обратная миграция: копируем первый QuestionFile обратно в data_file."""
    Question = apps.get_model('quizzes', 'Question')
    QuestionFile = apps.get_model('quizzes', 'QuestionFile')

    for qf in QuestionFile.objects.order_by('question_id', 'order', 'id'):
        Question.objects.filter(id=qf.question_id, data_file='').update(data_file=qf.file)


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_add_question_images_and_files'),
    ]

    operations = [
        migrations.RunPython(migrate_data_files, reverse_migrate),
    ]
