# Generated by Django 6.0.1 on 2026-02-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0019_migrate_data_file_to_question_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='data_file',
        ),
    ]
