# Generated by Django 6.0.1 on 2026-02-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0020_remove_question_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='alternative_answers',
            field=models.JSONField(blank=True, help_text='Список строк, например: ["42", "42.0"]', null=True, verbose_name='Альтернативные ответы'),
        ),
        migrations.AddField(
            model_name='question',
            name='ege_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер задачи ЕГЭ'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='exam_mode',
            field=models.CharField(blank=True, choices=[('exam', 'Экзамен'), ('practice', 'Тренировка')], default='practice', max_length=10, verbose_name='Режим ЕГЭ'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Доступен всем без назначения', verbose_name='Публичный доступ'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('standard', 'Стандартный'), ('exam', 'ЕГЭ')], default='standard', max_length=10, verbose_name='Тип теста'),
        ),
    ]
