# Generated by Django 6.0.1 on 2026-02-15 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_add_ege_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Время (секунды)')),
                ('attempts_to_solve', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Решена')),
                ('first_solved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время первого решения')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_progress', to='quizzes.question', verbose_name='Задача')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='quizzes.quiz', verbose_name='Вариант')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс задачи ЕГЭ',
                'verbose_name_plural': 'Прогресс задач ЕГЭ',
                'unique_together': {('user', 'quiz', 'question')},
            },
        ),
    ]
