# Generated by Django 6.0.1 on 2026-02-15 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0022_exam_task_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examtaskprogress',
            index=models.Index(fields=['user', 'quiz'], name='quizzes_exa_user_id_c88b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='examtaskprogress',
            index=models.Index(fields=['is_solved'], name='quizzes_exa_is_solv_16a7e5_idx'),
        ),
    ]
