# Generated by Django 6.0.1 on 2026-02-16 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_examtaskprogress_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='solutions/', verbose_name='Файл')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('image', models.ImageField(blank=True, null=True, upload_to='solutions/images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_attachments', to='quizzes.question', verbose_name='Задача')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_attachments', to='quizzes.quiz', verbose_name='Вариант')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доп. материал к решению',
                'verbose_name_plural': 'Доп. материалы к решениям',
                'unique_together': {('user', 'quiz', 'question')},
            },
        ),
    ]
