# Generated by Django 6.0.1 on 2026-02-16 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0024_solution_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='cpu_time_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='CPU-время (мс)'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='memory_kb',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пиковая память (КБ)'),
        ),
        migrations.CreateModel(
            name='SolutionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='quizzes.useranswer', verbose_name='Ответ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк решения',
                'verbose_name_plural': 'Лайки решений',
                'constraints': [models.UniqueConstraint(fields=('user', 'answer'), name='unique_solution_like')],
            },
        ),
    ]
