# Generated by Django 6.0.1 on 2026-02-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0025_add_cpu_memory_metrics_and_solution_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtaskprogress',
            name='best_cpu_time_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='Лучшее время CPU (мс)'),
        ),
        migrations.AddField(
            model_name='examtaskprogress',
            name='best_memory_kb',
            field=models.IntegerField(blank=True, null=True, verbose_name='Лучшая память (КБ)'),
        ),
    ]
