# Generated by Django 6.0.1 on 2026-02-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0026_add_best_metrics_to_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtaskprogress',
            name='best_cpu_code',
            field=models.TextField(blank=True, default='', verbose_name='Код лучшей попытки по CPU'),
        ),
        migrations.AddField(
            model_name='examtaskprogress',
            name='best_memory_code',
            field=models.TextField(blank=True, default='', verbose_name='Код лучшей попытки по памяти'),
        ),
    ]
