# Generated by Django 6.0.1 on 2026-02-22 14:31

import quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0027_add_best_code_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug (для медиа-путей)'),
        ),
        migrations.AlterField(
            model_name='questionfile',
            name='file',
            field=models.FileField(upload_to=quizzes.models.question_file_upload_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='questionimage',
            name='image',
            field=models.ImageField(upload_to=quizzes.models.question_image_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='solutionattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=quizzes.models.solution_file_upload_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='solutionattachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quizzes.models.solution_image_upload_path, verbose_name='Изображение'),
        ),
    ]
