# Generated by Django 6.0.1 on 2026-07-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0030_move_ege_media_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_self_check',
            field=models.BooleanField(default=False, help_text='Тест-самопроверка статьи учебника: доступен любому авторизованному ученику через статью, скрыт из общего списка тестов', verbose_name='Самопроверка учебника'),
        ),
    ]
