# Generated by Django 6.0.1 on 2026-08-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0031_quiz_is_self_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
    ]
