# Generated by Django 6.0.1 on 2026-08-19 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0032_alter_choice_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, default='', help_text='Markdown. Ученик не видит ни текста, ни самого факта наличия подсказки, пока она не откроется: три неудачные попытки, меньше трёх дней до дедлайна блока или рубильник в блоке.', verbose_name='Подсказка'),
        ),
        migrations.CreateModel(
            name='HintChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, verbose_name='Взял подсказку')),
                ('offered_at', models.DateTimeField(auto_now_add=True, verbose_name='Предложена')),
                ('decided_at', models.DateTimeField(auto_now=True, verbose_name='Последний выбор')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_choices', to='quizzes.question', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_choices', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Выбор по подсказке',
                'verbose_name_plural': 'Выборы по подсказкам',
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='unique_hint_choice')],
            },
        ),
    ]
