# Generated by Django 6.0.1 on 2026-08-26 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0034_alter_question_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок в сессии')),
                ('text_answer', models.CharField(blank=True, default='', max_length=200, verbose_name='Ответ ученика')),
                ('is_correct', models.BooleanField(help_text='Пусто – ученик ещё не отвечал.', null=True, verbose_name='Верно?')),
                ('seconds', models.PositiveIntegerField(default=0, verbose_name='Время на задачу (секунды)')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Момент ответа')),
            ],
            options={
                'verbose_name': 'Задача сессии',
                'verbose_name_plural': 'Задачи сессий',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('topic', 'По теме'), ('mistakes', 'Работа над ошибками'), ('mixed', 'Смешанная')], default='topic', max_length=10, verbose_name='Тип сессии')),
                ('mode', models.CharField(choices=[('study', 'Учёба'), ('exam', 'Экзамен')], default='study', max_length=10, verbose_name='Режим')),
                ('ege_number', models.PositiveSmallIntegerField(blank=True, help_text='Пусто для работы над ошибками и смешанной сессии – там задачи разных заданий.', null=True, verbose_name='Номер задания ЕГЭ')),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Базовая'), (2, 'Повышенная'), (3, 'Высокая')], help_text='Пусто – любая.', null=True, verbose_name='Сложность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Начата')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
            ],
            options={
                'verbose_name': 'Сессия тренировки ЕГЭ',
                'verbose_name_plural': 'Сессии тренировки ЕГЭ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Базовая'), (2, 'Повышенная'), (3, 'Высокая')], default=1, help_text='Стартовое значение из импорта. Фактическую сложность считает recalc_ege_difficulty по доле верных первых попыток.', verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='question',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID задачи на kompege.ru. По нему load_ege обновляет задачу вместо создания дубля при повторном импорте подборки.', max_length=64, verbose_name='ID на источнике'),
        ),
        migrations.AddField(
            model_name='question',
            name='solve_rate',
            field=models.FloatField(blank=True, help_text='Пересчитывается автоматически, когда наберётся достаточно попыток. Пусто – данных мало, сложность берётся из поля выше.', null=True, verbose_name='Доля верных первых попыток'),
        ),
        migrations.AddField(
            model_name='question',
            name='source_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на оригинал'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('standard', 'Стандартный'), ('exam', 'ЕГЭ'), ('bank', 'Банк задач ЕГЭ')], default='standard', max_length=10, verbose_name='Тип теста'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['ege_number', 'difficulty'], name='quizzes_que_ege_num_276a11_idx'),
        ),
        migrations.AddField(
            model_name='practiceitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_items', to='quizzes.question', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='practiceitem',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_items', to='quizzes.codesubmission', verbose_name='Отправка кода'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='practiceitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quizzes.practicesession', verbose_name='Сессия'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', '-created_at'], name='quizzes_pra_user_id_a7dc5f_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceitem',
            index=models.Index(fields=['session', 'order'], name='quizzes_pra_session_dbffde_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceitem',
            index=models.Index(fields=['question', 'is_correct'], name='quizzes_pra_questio_d75db5_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceitem',
            index=models.Index(fields=['answered_at'], name='quizzes_pra_answere_5d90e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='practiceitem',
            unique_together={('session', 'question')},
        ),
    ]
