# Generated by Django 6.0.1 on 2026-08-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0035_practiceitem_practicesession_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_only',
            field=models.BooleanField(db_index=True, default=False, help_text='Задача не попадает в учебные тренировки. Резерв нужен, чтобы режим «Экзамен» проверял знание темы, а не память о задачах, которые ученик уже прорешал на тренировках.', verbose_name='Только для экзамена'),
        ),
    ]
