# Generated by Django 6.0.1 on 2026-08-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0036_question_exam_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceitem',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Сколько раз ученик нажал «Проверить». При is_correct=True – с какой попытки решил.', verbose_name='Попыток'),
        ),
        migrations.AddField(
            model_name='practiceitem',
            name='gave_up',
            field=models.BooleanField(default=False, help_text='Ученик посмотрел верный ответ, не решив задачу. Считается как нерешённая.', verbose_name='Открыл ответ'),
        ),
    ]
