# Generated by Django 6.0.1 on 2026-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0037_practiceitem_attempts_practiceitem_gave_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='classroom_only',
            field=models.BooleanField(db_index=True, default=False, help_text='Задача выдаётся лишь по кнопке «Задачи для урока» и одна и та же у всех учеников. В обычные тренировки и в экзамен не попадает.', verbose_name='Только для работы в классе'),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='kind',
            field=models.CharField(choices=[('topic', 'По теме'), ('mistakes', 'Работа над ошибками'), ('mixed', 'Смешанная'), ('classroom', 'Работа в классе')], default='topic', max_length=10, verbose_name='Тип сессии'),
        ),
    ]
