# Generated by Django 6.0.1 on 2026-08-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0038_question_classroom_only_alter_practicesession_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='mode',
            field=models.CharField(choices=[('study', 'Тренировка'), ('exam', 'Экзамен')], default='study', max_length=10, verbose_name='Режим'),
        ),
    ]
