# Generated by Django 6.0.1 on 2026-08-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0039_alter_practicesession_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='kind',
            field=models.CharField(choices=[('topic', 'По теме'), ('mistakes', 'Работа над ошибками'), ('mixed', 'Смешанная'), ('classroom', 'Работа в классе'), ('retry', 'Переписать решение')], default='topic', max_length=10, verbose_name='Тип сессии'),
        ),
    ]
