# Generated by Django 6.0.1 on 2026-08-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0040_alter_practicesession_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Заполняется только там, где балл частичный (задания 26 и 27). Пусто – задача оценивается «верно/неверно».', null=True, verbose_name='Балл'),
        ),
        migrations.AddField(
            model_name='examtaskprogress',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Заполняется только там, где балл частичный (задания 26 и 27). Пусто – задача оценивается «верно/неверно».', null=True, verbose_name='Балл'),
        ),
        migrations.AddField(
            model_name='practiceitem',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Заполняется только там, где балл частичный (задания 26 и 27). Пусто – задача оценивается «верно/неверно».', null=True, verbose_name='Балл'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Заполняется только там, где балл частичный (задания 26 и 27). Пусто – задача оценивается «верно/неверно».', null=True, verbose_name='Балл'),
        ),
    ]
