# Generated by Django 6.0.1 on 2026-08-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0044_recount_code_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Задачи с одинаковым значением выдаются только вместе и в одном порядке. Так устроены задания 19–21: условие игры описано в 19-м, а 20-е и 21-е на него ссылаются. Пусто – задача сама по себе.', max_length=64, verbose_name='Связка задач'),
        ),
        migrations.AddField(
            model_name='question',
            name='group_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Порядок внутри связки: 0 – первая задача, за ней 1, 2. Без связки не используется.', verbose_name='Место в связке'),
        ),
    ]
