# Generated by Django 6.0.1 on 2026-08-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0045_question_group_id_question_group_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceitem',
            name='carried',
            field=models.BooleanField(db_index=True, default=False, help_text='Задача попала в сессию только как часть связки (19–21): ученик решил её раньше, ответ подставлен, решать заново нечего. В статистику и в работу над ошибками такая запись не идёт.', verbose_name='Ответ перенесён'),
        ),
    ]
