# Generated by Django 6.0.1 on 2026-08-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0046_practiceitem_carried'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='helpcomment',
            name='help_request',
        ),
        migrations.AlterUniqueTogether(
            name='helprequest',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='helprequest',
            name='quizzes_hel_status_3d17f6_idx',
        ),
        migrations.DeleteModel(
            name='HelpComment',
        ),
        migrations.DeleteModel(
            name='HelpRequest',
        ),
    ]
