# Generated by Django 6.0.1 on 2026-10-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0047_remove_helpcomment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('cpp', 'C++')], default='python', max_length=10, verbose_name='Язык'),
        ),
    ]
