# Generated by Django 6.0.1 on 2026-10-04 17:44

import quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0051_drop_old_solution_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedsolution',
            name='draft_comment',
            field=models.TextField(blank=True, default='', verbose_name='Разбор на проверке'),
        ),
        migrations.AddField(
            model_name='sharedsolution',
            name='draft_file',
            field=models.FileField(blank=True, null=True, upload_to=quizzes.models.solution_file_upload_path, verbose_name='Файл на проверке'),
        ),
        migrations.AddField(
            model_name='sharedsolution',
            name='draft_image',
            field=models.ImageField(blank=True, null=True, upload_to=quizzes.models.solution_image_upload_path, verbose_name='Картинка на проверке'),
        ),
        migrations.AddField(
            model_name='sharedsolution',
            name='review_note',
            field=models.TextField(blank=True, default='', help_text='Видит только автор – почему отклонён или что поправлено.', verbose_name='Слово учителя'),
        ),
        migrations.AddField(
            model_name='sharedsolution',
            name='review_status',
            field=models.CharField(blank=True, choices=[('', 'Нет на проверке'), ('pending', 'На проверке'), ('approved', 'Принят'), ('edited', 'Принят с правками учителя'), ('rejected', 'Отклонён')], db_index=True, default='', max_length=10, verbose_name='Проверка разбора'),
        ),
        migrations.AddField(
            model_name='sharedsolution',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлен на проверку'),
        ),
    ]
