# Generated by Django 6.0.1 on 2026-10-08 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0052_sharedsolution_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='check_quiz',
            field=models.ForeignKey(blank=True, help_text='Только у сессии среза: из какой работы она взята.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_sessions', to='quizzes.quiz', verbose_name='Срез'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='check_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Только для среза. Пусто – сумма нормативов ЕГЭ по номерам его задач.', null=True, verbose_name='Минут на срез'),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='kind',
            field=models.CharField(choices=[('topic', 'По теме'), ('mistakes', 'Работа над ошибками'), ('mixed', 'Смешанная'), ('classroom', 'Работа в классе'), ('retry', 'Переписать решение'), ('check', 'Срез')], default='topic', max_length=10, verbose_name='Тип сессии'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('standard', 'Стандартный'), ('exam', 'ЕГЭ'), ('bank', 'Банк задач ЕГЭ'), ('check', 'Срез ЕГЭ')], default='standard', max_length=10, verbose_name='Тип теста'),
        ),
    ]
