# Generated by Django 6.0.1 on 2026-05-03 03:05

import django.db.models.deletion
import games.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название темы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('moderator_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_si_categories', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название пакета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_si_packs', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Игровой пакет',
                'verbose_name_plural': 'Игровые пакеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_packs', to='games.category', verbose_name='Тема')),
                ('game_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_categories', to='games.gamepack', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Тема в пакете',
                'verbose_name_plural': 'Темы в пакете',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='gamepack',
            name='categories',
            field=models.ManyToManyField(through='games.GamePackCategory', to='games.category', verbose_name='Темы'),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_state', models.JSONField(default=dict, verbose_name='Состояние доски')),
                ('players', models.JSONField(default=list, verbose_name='Игроки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Начата')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='si_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
                ('game_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.gamepack', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('points', models.IntegerField(default=100, verbose_name='Стоимость')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.category', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('audio', 'Аудио'), ('video', 'Видео')], max_length=10, verbose_name='Тип медиа')),
                ('file', models.FileField(upload_to=games.models.question_media_upload_path, verbose_name='Файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='games.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Медиафайл вопроса',
                'verbose_name_plural': 'Медиафайлы вопросов',
                'ordering': ['media_type', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['status'], name='games_categ_status_f4e428_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_by', 'status'], name='games_categ_created_7bca9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gamepackcategory',
            unique_together={('game_pack', 'category')},
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['created_by', 'is_active'], name='games_games_created_6806f0_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['game_pack', 'is_active'], name='games_games_game_pa_e96a4a_idx'),
        ),
    ]
