# Generated by Django 6.0.1 on 2026-01-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons_files/', verbose_name='Файл с материалами'),
        ),
    ]
