# Generated by Django 6.0.1 on 2026-01-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_section_lesson_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание и материалы'),
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('text_image', 'Текст + Изображение')], default='text', max_length=20, verbose_name='Тип блока')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons_content/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Блок урока',
                'verbose_name_plural': 'Блоки урока',
                'ordering': ['order'],
            },
        ),
    ]
