# Generated by Django 6.0.1 on 2026-01-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_options_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonblock',
            name='image_width',
            field=models.PositiveIntegerField(default=50, verbose_name='Ширина изображения (%)'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='layout',
            field=models.CharField(choices=[('vertical', 'Вертикально'), ('horizontal', 'Горизонтально (текст слева)'), ('horizontal-reverse', 'Горизонтально (картинка слева)')], default='vertical', max_length=20, verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='text_align',
            field=models.CharField(choices=[('left', 'По левому краю'), ('center', 'По центру'), ('right', 'По правому краю')], default='left', max_length=10, verbose_name='Выравнивание текста'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
    ]
