# Generated by Django 6.0.1 on 2026-01-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lessonblock_image_width_lessonblock_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonblock',
            name='image_align',
            field=models.CharField(choices=[('left', 'Слева'), ('center', 'По центру'), ('right', 'Справа')], default='center', max_length=10, verbose_name='Выравнивание изображения'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='image_height',
            field=models.PositiveIntegerField(default=0, help_text='0 = авто', verbose_name='Высота изображения (px)'),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='image_width',
            field=models.PositiveIntegerField(default=100, verbose_name='Ширина изображения (%)'),
        ),
    ]
