# Generated by Django 6.0.1 on 2026-01-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_lessonblock_image_pos_x_lessonblock_image_pos_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='preview_description',
            field=models.CharField(blank=True, help_text='Отображается в карточке урока (до 200 символов)', max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Отображается в карточке урока в списке', null=True, upload_to='lesson_previews/', verbose_name='Превью изображение'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo или прямая ссылка (на будущее)', verbose_name='URL видео'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='card_bg',
            field=models.CharField(choices=[('bg-white', 'Белый'), ('bg-gray-50', 'Светло-серый'), ('bg-gray-100', 'Серый'), ('bg-blue-50', 'Светло-синий'), ('bg-green-50', 'Светло-зелёный'), ('bg-yellow-50', 'Светло-жёлтый'), ('bg-red-50', 'Светло-красный'), ('bg-purple-50', 'Светло-фиолетовый')], default='bg-white', max_length=30, verbose_name='Фон карточки'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='content_color',
            field=models.CharField(choices=[('text-gray-900', 'Чёрный'), ('text-gray-700', 'Тёмно-серый'), ('text-gray-500', 'Серый'), ('text-white', 'Белый'), ('text-blue-600', 'Синий'), ('text-green-600', 'Зелёный'), ('text-red-600', 'Красный'), ('text-yellow-600', 'Жёлтый'), ('text-purple-600', 'Фиолетовый'), ('text-pink-600', 'Розовый')], default='text-gray-700', max_length=30, verbose_name='Цвет текста'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='content_font_family',
            field=models.CharField(choices=[('font-sans', 'Sans-serif (Inter)'), ('font-serif', 'Serif (Georgia)'), ('font-mono', 'Monospace')], default='font-sans', max_length=20, verbose_name='Шрифт текста'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='content_font_size',
            field=models.CharField(choices=[('text-sm', 'Маленький'), ('text-base', 'Обычный'), ('text-lg', 'Увеличенный'), ('text-xl', 'Большой'), ('text-2xl', 'Очень большой'), ('text-3xl', 'Огромный')], default='text-base', max_length=20, verbose_name='Размер текста'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='title_color',
            field=models.CharField(choices=[('text-gray-900', 'Чёрный'), ('text-gray-700', 'Тёмно-серый'), ('text-gray-500', 'Серый'), ('text-white', 'Белый'), ('text-blue-600', 'Синий'), ('text-green-600', 'Зелёный'), ('text-red-600', 'Красный'), ('text-yellow-600', 'Жёлтый'), ('text-purple-600', 'Фиолетовый'), ('text-pink-600', 'Розовый')], default='text-gray-900', max_length=30, verbose_name='Цвет заголовка'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='title_font_family',
            field=models.CharField(choices=[('font-sans', 'Sans-serif (Inter)'), ('font-serif', 'Serif (Georgia)'), ('font-mono', 'Monospace')], default='font-sans', max_length=20, verbose_name='Шрифт заголовка'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='title_font_size',
            field=models.CharField(choices=[('text-sm', 'Маленький'), ('text-base', 'Обычный'), ('text-lg', 'Увеличенный'), ('text-xl', 'Большой'), ('text-2xl', 'Очень большой'), ('text-3xl', 'Огромный')], default='text-xl', max_length=20, verbose_name='Размер заголовка'),
        ),
    ]
