# Generated by Django 6.0.1 on 2026-03-09 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_lesson_preview_description_lesson_preview_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='presentation_pdf',
            field=models.FileField(blank=True, upload_to='lessons_presentations/', verbose_name='PDF презентации'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='presentation_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название презентации'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='presentation_url',
            field=models.CharField(blank=True, help_text='Путь Nginx, например /slides/writer/', max_length=300, verbose_name='URL презентации'),
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lessons_files/', verbose_name='Файл')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['order'],
            },
        ),
    ]
