# Generated by Django 6.0.1 on 2026-03-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_migrate_lesson_files_to_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='file',
        ),
    ]
