# Generated by Django 6.0.1 on 2026-03-09 03:54

import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_remove_lesson_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='presentation_pdf',
            field=models.FileField(blank=True, upload_to=lessons.models.lesson_file_upload, verbose_name='PDF презентации'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='presentation_url',
            field=models.CharField(blank=True, help_text='Путь к презентации, например /media/lessons/Writer/presentation/', max_length=300, verbose_name='URL презентации'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Отображается в карточке урока в списке', null=True, upload_to=lessons.models.lesson_file_upload, verbose_name='Превью изображение'),
        ),
        migrations.AlterField(
            model_name='lessonattachment',
            name='file',
            field=models.FileField(upload_to=lessons.models.lesson_attachment_upload, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lessons.models.lesson_block_image_upload, verbose_name='Изображение'),
        ),
    ]
